# Generated by Django 3.2.6 on 2021-08-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imge',
            new_name='img',
        ),
    ]
