# Generated by Django 3.2.5 on 2021-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_imge_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malumotjonat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrez', models.PositiveIntegerField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.PositiveIntegerField(max_length=100)),
            ],
        ),
    ]
